type text = {
	word: string;
	sentence: string;
};
export function getWords(length = 40, tabname = "word") {
	const array: string[] = [];
	if (tabname == "sentence") length = length / 5;
	while (length--) {
		const randomIndex = Math.floor(Math.random() * words.length);
		if (tabname === "word") {
			var word = words[randomIndex].word.split("");
		} else {
			var word = words[randomIndex].sentence.split("");
		}
		word.forEach((letter) => {
			array.push(letter);
		});
		array.push(" ");
	}
	return array;
}
export const words: text[] = [
	{ word: "be", sentence: "Will you be my friend?" },
	{ word: "and", sentence: "You and I will always be friends." },
	{ word: "of", sentence: "Today is the first of November." },
	{ word: "a", sentence: "I saw a bear today." },
	{ word: "in", sentence: "She is in her room." },
	{ word: "to", sentence: "Let's go to the park." },
	{ word: "have", sentence: "I have a few questions." },
	{ word: "too", sentence: "I like her too." },
	{ word: "it", sentence: "It is sunny outside." },
	{ word: "I", sentence: "I really like it here." },
	{ word: "that", sentence: "That door is open." },
	{ word: "for", sentence: "This letter is for you." },
	{ word: "you", sentence: "You are really nice." },
	{ word: "he", sentence: "He is my brother." },
	{ word: "with", sentence: "I want to go with you." },
	{ word: "on", sentence: "I watch movies on my iPad." },
	{ word: "do", sentence: "What will you do now?" },
	{ word: "say", sentence: "Can I say something?" },
	{ word: "this", sentence: "This is my favorite cookie." },
	{ word: "they", sentence: "They are here!" },
	{ word: "at", sentence: "Can you pick me up at the mall?" },
	{ word: "but", sentence: "I'm sorry but she's away." },
	{ word: "we", sentence: "We are going to watch a movie." },
	{ word: "his", sentence: "This is his box." },
	{ word: "from", sentence: "This card came from my cousin." },
	{ word: "that", sentence: "That's a really cool trick!" },
	{ word: "not", sentence: "That's not what I want." },
	{ word: "can't", sentence: "I can't open it." },
	{ word: "won't", sentence: "I won't open it." },
	{ word: "by", sentence: "Will you come by and see me?" },
	{ word: "she", sentence: "She is very happy." },
	{ word: "or", sentence: "Do you like blue or yellow?" },
	{
		word: "as",
		sentence: "Her role as an English teacher is very important.",
	},
	{ word: "what", sentence: "What are you thinking of?" },
	{ word: "go", sentence: "I want to go there." },
	{ word: "their", sentence: "This is their house." },
	{ word: "can", sentence: "What can I do for you?" },
	{ word: "who", sentence: "Who can help me?" },
	{ word: "get", sentence: "Can you get me my eyeglasses?" },
	{ word: "if", sentence: "What if I fail?" },
	{ word: "would", sentence: "Would you help me out?" },
	{ word: "her", sentence: "I have her book." },
	{ word: "all", sentence: "All my favorite books are on this shelf." },
	{ word: "my", sentence: "My mom is coming to visit." },
	{ word: "make", sentence: "Can we make our projects together?" },
	{ word: "about", sentence: "What is this movie about?" },
	{ word: "know", sentence: "Do you know where this place is?" },
	{ word: "will", sentence: "I will help you find that place." },
	{ word: "as", sentence: "As soon as she's here, I'll talk to her." },
	{ word: "up", sentence: "I live up in the mountains." },
	{ word: "one", sentence: "She is one of my English teachers." },
	{ word: "time", sentence: "There was a time I liked to play golf." },
	{ word: "there", sentence: "There are so many things I want to learn." },
	{
		word: "year",
		sentence: "This is the year I'm finally going to learn English.",
	},
	{ word: "so", sentence: "I am so sorry." },
	{ word: "think", sentence: "I think I need to lie down." },
	{ word: "when", sentence: "When will I see you again?" },
	{ word: "which", sentence: "Which of these slippers are yours?" },
	{ word: "them", sentence: "Please give this to them." },
	{
		word: "some",
		sentence: "Please give them some of the apples I brought home.",
	},
	{ word: "me", sentence: "Can you give me some apples?" },
	{ word: "people", sentence: "There are so many people at the mall today." },
	{ word: "take", sentence: "Please take home some of these apples" },
	{ word: "out", sentence: "Please throw the trash out." },
	{ word: "into", sentence: "My puppy ran into the woods." },
	{ word: "just", sentence: "Just close your eyes." },
	{ word: "see", sentence: "Did you see that?" },
	{ word: "him", sentence: "I heard him singing earlier." },
	{ word: "your", sentence: "Your mom is here." },
	{ word: "come", sentence: "Can your mom and dad come to the party?" },
	{ word: "could", sentence: "Could you help me with my project?" },
	{ word: "now", sentence: "I want to watch this now." },
	{
		word: "than",
		sentence: "I like this cake better than the other one you showed me.",
	},
	{
		word: "like",
		sentence: "I like this bag better than the other one you showed me.",
	},
	{
		word: "other",
		sentence:
			"I like these shoes better than the other ones you showed me.",
	},
	{ word: "how", sentence: "How do I turn this on?" },
	{ word: "then", sentence: "We had breakfast and then we went to church." },
	{ word: "its", sentence: "I need to read its manual." },
	{ word: "our", sentence: "This is our home now." },
	{ word: "two", sentence: "Two cheeseburgers, please." },
	{ word: "more", sentence: "Can I have some more milk shake?" },
	{ word: "these", sentence: "Do you like these ribbons?" },
	{ word: "want", sentence: "Do you want these ribbons?" },
	{ word: "way", sentence: "Can you look this way?" },
	{ word: "look", sentence: "Please look this way." },
	{ word: "first", sentence: "She was my very first teacher." },
	{ word: "also", sentence: "She was also my best friend." },
	{ word: "new", sentence: "I have new shoes." },
	{ word: "because", sentence: "I am crying because I'm sad." },
	{ word: "day", sentence: "Today is National Friendship day." },
	{ word: "more", sentence: "I have more stickers at home." },
	{ word: "use", sentence: "How do I use this?" },
	{ word: "no", sentence: "There's no electricity now." },
	{ word: "man", sentence: "There's a man outside looking for you." },
	{ word: "find", sentence: "Where can I find rare furniture?" },
	{ word: "here", sentence: "My mom is here." },
	{ word: "thing", sentence: "One thing led to another." },
	{ word: "give", sentence: "Give her these pearls." },
	{ word: "many", sentence: "We shared many dreams together." },
	{ word: "well", sentence: "You know me so well." },
	{ word: "only", sentence: "You are my only friend here." },
	{ word: "those", sentence: "Those boots belong to my friend." },
	{ word: "tell", sentence: "Can you tell me which way to go?" },
	{ word: "one", sentence: "She's the one he's been waiting for." },
	{ word: "very", sentence: "I'm very upset right now." },
	{ word: "her", sentence: "Her grandmother is sick." },
	{ word: "even", sentence: "She can't even stand on her own." },
	{ word: "back", sentence: "I'll be right back." },
	{ word: "any", sentence: "Have you had any luck on your research?" },
	{ word: "good", sentence: "You're a good person." },
	{ word: "woman", sentence: "That woman looks so polished." },
	{
		word: "through",
		sentence: "Your faith will see you through tough times.",
	},
	{ word: "us", sentence: "Do you want to go with us?" },
	{ word: "life", sentence: "This is the best day of my life." },
	{
		word: "child",
		sentence: "I just saw a child cross the street by herself.",
	},
	{ word: "there", sentence: "Did you go there?" },
	{ word: "work", sentence: "I have to go to work." },
	{ word: "down", sentence: "Let's go down." },
	{ word: "may", sentence: "You may take your seats." },
	{ word: "after", sentence: "Let's have dinner after work." },
	{ word: "should", sentence: "Should I buy this dress?" },
	{ word: "call", sentence: "Call me when you get home, okay?" },
	{ word: "world", sentence: "I want to travel and see the world." },
	{ word: "over", sentence: "I can't wait for this day to be over." },
	{ word: "school", sentence: "My cousin goes to school here." },
	{ word: "still", sentence: "I still think you should go." },
	{ word: "try", sentence: "Can you try to be nicer to him?" },
	{ word: "in", sentence: "What's in that box?" },
	{
		word: "as",
		sentence:
			"As soon as I get home, I'm going to start watching that series.",
	},
	{ word: "last", sentence: "This is my last slice of cake, I promise!" },
	{ word: "ask", sentence: "Can you ask the waiter to bring us some wine?" },
	{ word: "need", sentence: "I need some wine tonight!" },
	{ word: "too", sentence: "I need some wine, too!" },
	{
		word: "feel",
		sentence: "I feel so tired, I just need to relax and unwind.",
	},
	{ word: "three", sentence: "I have three sisters." },
	{ word: "when", sentence: "When was the last time you saw them?" },
	{
		word: "state",
		sentence: "Check out the state of that shed, it's falling apart.",
	},
	{ word: "never", sentence: "I'm never going to drink wine again." },
	{ word: "become", sentence: "Over the years we've become really close." },
	{ word: "between", sentence: "This is just between you and me." },
	{ word: "high", sentence: "Give me a high five!" },
	{ word: "really", sentence: "I really like your painting!" },
	{ word: "something", sentence: "I have something for you." },
	{ word: "most", sentence: "She's the most beautiful girl I've ever seen." },
	{ word: "another", sentence: "I'll have another glass of wine, please." },
	{ word: "much", sentence: "I love you guys so much." },
	{ word: "family", sentence: "You are like family to me." },
	{ word: "own", sentence: "I want to get my own place." },
	{ word: "out", sentence: "Get out of my room." },
	{ word: "leave", sentence: "I want you to leave." },
	{ word: "put", sentence: "Please put down that book and listen to me." },
	{ word: "old", sentence: "I feel so old!" },
	{ word: "while", sentence: "I can wait for you here while you shop." },
	{ word: "mean", sentence: "I didn't mean to sound so angry." },
	{ word: "on", sentence: "Can you turn on the lights?" },
	{ word: "keep", sentence: "Can we keep the lights on tonight?" },
	{ word: "student", sentence: "I've always been a diligent student." },
	{ word: "why", sentence: "This is why I don't go out anymore." },
	{ word: "let", sentence: "Why won't you let him know how you feel?" },
	{
		word: "great",
		sentence: "This ice cream place is great for families with kids!",
	},
	{ word: "same", sentence: "Hey, we're wearing the same shirt!" },
	{ word: "big", sentence: "I have this big crush on Brad Pitt." },
	{
		word: "group",
		sentence: "The group sitting across our table is so noisy.",
	},
	{ word: "begin", sentence: "Where do I begin with this huge project?" },
	{
		word: "seem",
		sentence:
			"She may seem quiet, but she's really outgoing once you get to know her.",
	},
	{ word: "country", sentence: "Japan is such a beautiful country!" },
	{ word: "help", sentence: "I need help with my Math homework." },
	{ word: "talk", sentence: "Can we talk in private?" },
	{ word: "where", sentence: "Where were you last night?" },
	{ word: "turn", sentence: "If only I could turn back time." },
	{
		word: "problem",
		sentence: "The problem is we think we have plenty of time.",
	},
	{
		word: "every",
		sentence: "Every person has his own big goal to fulfill.",
	},
	{
		word: "start",
		sentence: "This is a great to start to learn the English language.",
	},
	{ word: "hand", sentence: "Don't let go of my hand." },
	{ word: "might", sentence: "This might actually work." },
	{ word: "American", sentence: "The American culture is so dynamic." },
	{
		word: "show",
		sentence: "Can you show me how to use this vacuum cleaner?",
	},
	{ word: "part", sentence: "This is my favorite part of the movie!" },
	{ word: "about", sentence: "What is the story about?" },
	{ word: "against", sentence: "I am so against domestic abuse!" },
	{ word: "place", sentence: "This place is wonderful!" },
	{ word: "over", sentence: "She kept saying this over and over again." },
	{ word: "such", sentence: "He is such an annoying person." },
	{ word: "again", sentence: "Can we play that game again?" },
	{ word: "few", sentence: "Just a few more errands and I'm done!" },
	{
		word: "case",
		sentence: "What an interesting case you are working on now!",
	},
	{
		word: "most",
		sentence: "That's the most interesting story I've ever heard.",
	},
	{ word: "week", sentence: "I had a rough week." },
	{ word: "company", sentence: "Will you keep me company?" },
	{ word: "where", sentence: "Where are we going?" },
	{ word: "system", sentence: "What's wrong with the airport's system?" },
	{ word: "each", sentence: "Can you give each of them an apple?" },
	{ word: "right", sentence: "I'm right this time." },
	{
		word: "program",
		sentence: "This community program for teens is really helpful.",
	},
	{ word: "hear", sentence: "Did you hear that?" },
	{ word: "so", sentence: "I'm so sleepy." },
	{ word: "question", sentence: "I have a question for you." },
	{ word: "during", sentence: "During the session, I saw him fall asleep." },
	{ word: "work", sentence: "I have to work this weekend." },
	{ word: "play", sentence: "We can play soccer next weekend instead." },
	{
		word: "government",
		sentence:
			"I hope the government does something about the poverty in this country.",
	},
	{ word: "run", sentence: "If you see a bear here, run for your life." },
	{ word: "small", sentence: "I have a small favor to ask you." },
	{ word: "number", sentence: "I have a number of favors to ask you." },
	{ word: "off", sentence: "Please turn off the television." },
	{ word: "always", sentence: "I always bring pepper spray with me." },
	{ word: "move", sentence: "Let's move on to the next tourist spot." },
	{ word: "like", sentence: "I really like you." },
	{ word: "night", sentence: "The night is young." },
	{ word: "live", sentence: "I'm going to live like there's no tomorrow." },
	{ word: "Mr", sentence: "Mr. Morris is here." },
	{ word: "point", sentence: "You have a point." },
	{ word: "believe", sentence: "I believe in you." },
	{ word: "hold", sentence: "Just hold my hand." },
	{ word: "today", sentence: "I'm going to see you today." },
	{ word: "bring", sentence: "Please bring a pen." },
	{
		word: "happen",
		sentence: "What will happen if you don't submit your report on time?",
	},
	{ word: "next", sentence: "This is the next best thing." },
	{ word: "without", sentence: "I can't live without my phone." },
	{ word: "before", sentence: "Before I go to bed I always wash my face." },
	{
		word: "large",
		sentence: "There's a large amount of data online about that topic.",
	},
	{ word: "all", sentence: "That's all I know about Dinosaurs." },
	{
		word: "million",
		sentence: "I have a million questions about this book.",
	},
	{ word: "must", sentence: "We must watch this movie together." },
	{ word: "home", sentence: "Can we go home now?" },
	{ word: "under", sentence: "I hid it under my bed." },
	{ word: "water", sentence: "I filled the tub with water." },
	{ word: "room", sentence: "His room is at the end of the corridor." },
	{ word: "write", sentence: "Can you write me a prescription for this?" },
	{ word: "mother", sentence: "His mother is a very lovely woman." },
	{ word: "area", sentence: "This area of this house needs to be fixed." },
	{ word: "national", sentence: "That virus has become a national concern." },
	{ word: "money", sentence: "She needs money to buy her medicine." },
	{ word: "story", sentence: "She shared her story to the media." },
	{ word: "young", sentence: "She is so young and so hopeful." },
	{ word: "fact", sentence: "It's a fact: shopping can improve your mood." },
	{ word: "month", sentence: "It's that time of the month!" },
	{
		word: "different",
		sentence: "Just because she's different, it doesn't mean she's bad.",
	},
	{ word: "lot", sentence: "You have a lot of explaining to do." },
	{ word: "right", sentence: "Turn right when you reach the corner." },
	{ word: "study", sentence: "Let's study our English lessons together." },
	{ word: "book", sentence: "Can I borrow your English book?" },
	{ word: "eye", sentence: "She has the pink eye." },
	{ word: "job", sentence: "I love my job." },
	{ word: "word", sentence: "Describe yourself in one word." },
	{
		word: "though",
		sentence:
			"Though you are angry now, I'm sure you will forget about this later.",
	},
	{ word: "business", sentence: "His business is thriving." },
	{ word: "issue", sentence: "This is not an issue for me." },
	{ word: "side", sentence: "Whose side are you on, anyway?" },
	{ word: "kind", sentence: "Always be kind, even to strangers." },
	{ word: "four", sentence: "There are four seasons in a year." },
	{ word: "head", sentence: "Let's head back, it's freezing out here." },
	{ word: "far", sentence: "We've gone too far and now we're lost." },
	{ word: "black", sentence: "She has long, black hair." },
	{ word: "long", sentence: "She has long, brown hair." },
	{ word: "both", sentence: "They both love chocolate ice cream." },
	{ word: "little", sentence: "I have two little boys with me now." },
	{ word: "house", sentence: "The house is so quiet without you." },
	{ word: "yes", sentence: "I hope you say yes." },
	{
		word: "after",
		sentence: "After all this time, he has finally learned to love.",
	},
	{
		word: "since",
		sentence:
			"Ever since his mom died, he has been cranky and angry at the world.",
	},
	{ word: "long", sentence: "That was such a long time ago." },
	{
		word: "provide",
		sentence: "Please provide me with a list of your services.",
	},
	{
		word: "service",
		sentence: "Do you have a specific dental service to treat this?",
	},
	{ word: "around", sentence: "We went around the block." },
	{ word: "friend", sentence: "You're a good friend." },
	{ word: "important", sentence: "You're important to me." },
	{ word: "father", sentence: "My father is so important to me." },
	{ word: "sit", sentence: "Let's sit outside together." },
	{ word: "away", sentence: "He's away right now." },
	{ word: "until", sentence: "Until when will you be away?" },
	{ word: "power", sentence: "With great power comes great responsibility." },
	{
		word: "hour",
		sentence: "I've been checking his temperature every hour.",
	},
	{ word: "game", sentence: "Let's play a game." },
	{ word: "often", sentence: "I buy from his bakery as often as I can." },
	{ word: "yet", sentence: "He's not yet home." },
	{ word: "line", sentence: "There's a long line at the grocery cashier." },
	{ word: "political", sentence: "I stay away from political discussions." },
	{ word: "end", sentence: "It's the end of an era." },
	{ word: "among", sentence: "Among all my pets, he's my most favorite." },
	{ word: "ever", sentence: "Have you ever tried this cake?" },
	{ word: "stand", sentence: "Can you stand still for a minute?" },
	{ word: "bad", sentence: "What you did was so bad." },
	{ word: "lose", sentence: "I can't lose you." },
	{
		word: "however",
		sentence:
			"I want to buy this bag, however, I need to save up for it first.",
	},
	{ word: "member", sentence: "She's a member of the babysitter's club." },
	{ word: "pay", sentence: "Let's pay for our groceries." },
	{ word: "law", sentence: "There's a law against jay-walking." },
	{ word: "meet", sentence: "I want you to meet my aunt." },
	{ word: "car", sentence: "Let's go inside my car." },
	{ word: "city", sentence: "This is the city that never sleeps." },
	{ word: "almost", sentence: "I'm almost done with my report." },
	{
		word: "include",
		sentence: "Did you remember to include the summary in your report?",
	},
	{ word: "continue", sentence: "Can we continue working tomorrow?" },
	{ word: "set", sentence: "Great, let me set an appointment for you." },
	{ word: "later", sentence: "I'll finish it later." },
	{ word: "community", sentence: "Our community is very tight knit." },
	{
		word: "much",
		sentence: "There's so much to learn in the English language.",
	},
	{ word: "name", sentence: "What's your name?" },
	{
		word: "five",
		sentence:
			"I can give you five reasons why you need to watch that video.",
	},
	{ word: "once", sentence: "I once had a puppy named Bark." },
	{ word: "white", sentence: "I love my white sneakers." },
	{
		word: "least",
		sentence: "She's the least productive among all the employees.",
	},
	{
		word: "president",
		sentence: "She was our class president back in high school.",
	},
	{
		word: "learn",
		sentence: "I'd love to learn more about the English language.",
	},
	{ word: "real", sentence: "What is her real name?" },
	{
		word: "change",
		sentence: "What can we change so that things will get better?",
	},
	{
		word: "team",
		sentence: "They hired a team to do the design of their new office.",
	},
	{ word: "minute", sentence: "She's laughing every minute of every day." },
	{
		word: "best",
		sentence: "This is the best potato salad I've ever tasted.",
	},
	{
		word: "several",
		sentence: "I have several old clothes I need to donate.",
	},
	{
		word: "idea",
		sentence: "It was your idea to go to the beach, remember?",
	},
	{ word: "kid", sentence: "I loved that toy when I was a kid." },
	{ word: "body", sentence: "She worked out hard to achieve a toned body." },
	{ word: "information", sentence: "This is the information I need." },
	{
		word: "nothing",
		sentence: "There's nothing we can do now. , sentence :",
	},
	{
		word: "ago",
		sentence: "Three years ago, I visited Japan for the first time.",
	},
	{ word: "right", sentence: "You're right, I want to go back there." },
	{ word: "lead", sentence: "Just lead the way and I'll follow." },
	{ word: "social", sentence: "I feel awkward in these social gatherings." },
	{ word: "understand", sentence: "I understand how you feel." },
	{
		word: "whether",
		sentence:
			"Whether in big groups or small groups, I always feel a little shy at first.",
	},
	{
		word: "back",
		sentence: "Looking back, I knew I was always an introvert.",
	},
	{ word: "watch", sentence: "Let's watch the sun set on the horizon." },
	{ word: "together", sentence: "They're together now." },
	{ word: "follow", sentence: "I'll follow you home." },
	{ word: "around", sentence: "You'll always have me around." },
	{
		word: "parent",
		sentence: "Every parent is trying hard and doing their best.",
	},
	{ word: "only", sentence: "You are only allowed to go out today." },
	{ word: "stop", sentence: "Please stop that." },
	{ word: "face", sentence: "Why is your face so red?" },
	{ word: "anything", sentence: "You can ask me for anything." },
	{
		word: "create",
		sentence: "Did you create that presentation? It was so good.",
	},
	{ word: "public", sentence: "This is public property." },
	{ word: "already", sentence: "I already asked him to resend his report." },
	{ word: "speak", sentence: "Could you speak a little louder?" },
	{ word: "others", sentence: "The others haven't arrived yet." },
	{ word: "read", sentence: "I read somewhere that this house is haunted." },
	{ word: "level", sentence: "What level are you in that game?" },
	{
		word: "allow",
		sentence: "Do you allow your kids to play outside the house?",
	},
	{
		word: "add",
		sentence: "Is it okay if we add a bit of sugar to the tea?",
	},
	{ word: "office", sentence: "Welcome to my office." },
	{
		word: "spend",
		sentence: "How much did you spend on your last shopping spree?",
	},
	{ word: "door", sentence: "You left the door open." },
	{ word: "health", sentence: "You must take good care of your health." },
	{ word: "person", sentence: "You are a good person." },
	{ word: "art", sentence: "This is my work of art." },
	{ word: "sure", sentence: "Are you sure you want to do this alone?" },
	{ word: "such", sentence: "You are such a brave little boy." },
	{ word: "war", sentence: "The war has finally ended." },
	{ word: "history", sentence: "She is my history professor." },
	{ word: "party", sentence: "Are you going to her party tonight?" },
	{
		word: "within",
		sentence: "We support everyone within our small community.",
	},
	{
		word: "grow",
		sentence: "We want everyone to grow and thrive in their careers.",
	},
	{
		word: "result",
		sentence: "The result of this outreach program is amazing.",
	},
	{ word: "open", sentence: "Are you open to teaching on weekends?" },
	{ word: "change", sentence: "Where can we change her diaper?" },
	{ word: "morning", sentence: "It's such a beautiful morning!" },
	{ word: "walk", sentence: "Come take a walk with me." },
	{ word: "reason", sentence: "You are the reason I came home." },
	{ word: "low", sentence: "Her blood pressure has gotten really low." },
	{ word: "win", sentence: "We can win this match if we work together." },
	{ word: "research", sentence: "How is your research going?" },
	{ word: "girl", sentence: "That girl is in my class." },
	{ word: "guy", sentence: "I've seen that guy in school before." },
	{ word: "early", sentence: "I come to work so early every day." },
	{ word: "food", sentence: "Let's buy some food, I'm hungry!" },
	{ word: "before", sentence: "Can I talk to you before you go home?" },
	{
		word: "moment",
		sentence:
			"The moment she walked in the room, her puppy started to jump and dance again.",
	},
	{ word: "himself", sentence: "He cooked this Turkey himself." },
	{ word: "air", sentence: "I am loving the cold night air here." },
	{ word: "teacher", sentence: "You are the best teacher ever." },
	{ word: "force", sentence: "Don't force him to play with other kids." },
	{ word: "offer", sentence: "Can I offer you a ride home?" },
	{ word: "enough", sentence: "Boys, that's enough playing for today." },
	{
		word: "both",
		sentence: "You both need to change into your sleep clothes now.",
	},
	{
		word: "education",
		sentence: "I just want you to get the best education.",
	},
	{ word: "across", sentence: "Your dog ran across the park." },
	{
		word: "although",
		sentence: "Although she felt tired, she still couldn't sleep.",
	},
	{
		word: "remember",
		sentence: "Do you think she will still remember me after ten years?",
	},
	{ word: "foot", sentence: "Her foot got caught in one of the ropes." },
	{
		word: "second",
		sentence: "This is the second time she got late this month.",
	},
	{
		word: "boy",
		sentence: "There's a boy in her class who keeps pulling her hair.",
	},
	{ word: "maybe", sentence: "Maybe we can have ice cream for dessert." },
	{ word: "toward", sentence: "He took a step toward her." },
	{
		word: "able",
		sentence: "Will you be able to send me your report today?",
	},
	{ word: "age", sentence: "What is the average marrying age these days?" },
	{ word: "off", sentence: "The cat ran off with the dog." },
	{ word: "policy", sentence: "They have a generous return policy." },
	{ word: "everything", sentence: "Everything is on sale." },
	{ word: "love", sentence: "I love what you're wearing!" },
	{
		word: "process",
		sentence: "Wait, give me time to process everything you're telling me.",
	},
	{ word: "music", sentence: "I love music." },
	{
		word: "including",
		sentence: "Around 20 people attended, including Bob and Beth.",
	},
	{ word: "consider", sentence: "I hope you consider my project proposal." },
	{ word: "appear", sentence: "How did that appear out of nowhere?" },
	{ word: "actually", sentence: "I'm actually just heading out." },
	{ word: "buy", sentence: "I'm going to buy these shoes." },
	{ word: "probably", sentence: "He's probably still asleep." },
	{ word: "human", sentence: "Give him a break, he is only human." },
	{ word: "wait", sentence: "Is it alright if you wait for a few minutes?" },
	{
		word: "serve",
		sentence: "This blow dryer has served me well for years.",
	},
	{ word: "market", sentence: "Let's visit the Sunday market." },
	{
		word: "die",
		sentence:
			"I don't want my cat to die, let's take him to the vet please.",
	},
	{ word: "send", sentence: "Please send the package to my address." },
	{
		word: "expect",
		sentence: "You can't expect much from their poor service.",
	},
	{ word: "home", sentence: "I can't wait to go home!" },
	{ word: "sense", sentence: "I did sense that something was not okay." },
	{ word: "build", sentence: "He is going to build his dream house." },
	{ word: "stay", sentence: "You can stay with me for a few weeks." },
	{ word: "fall", sentence: "Be careful, you might fall." },
	{ word: "oh", sentence: "Oh no, I left my phone at home!" },
	{ word: "nation", sentence: "We have to act as one nation." },
	{ word: "plan", sentence: "What's your plan this time?" },
	{ word: "cut", sentence: "Don't cut your hair." },
	{ word: "college", sentence: "We met in college." },
	{ word: "interest", sentence: "Music is an interest of mine." },
	{ word: "death", sentence: "Death is such a heavy topic for me." },
	{ word: "course", sentence: "What course did you take up in college?" },
	{ word: "someone", sentence: "Is there someone who can go with you?" },
	{ word: "experience", sentence: "What an exciting experience!" },
	{
		word: "behind",
		sentence: "I'm scared to check what's behind that door.",
	},
	{
		word: "reach",
		sentence: "I can't reach him, he won't answer his phone.",
	},
	{ word: "local", sentence: "This is a local business." },
	{ word: "kill", sentence: "Smoking can kill you." },
	{ word: "six", sentence: "I have six books about Psychology." },
	{ word: "remain", sentence: "These remain on the top shelf." },
	{ word: "effect", sentence: "Wow, the effect of that mascara is great!" },
	{ word: "use", sentence: "Can I use your phone?" },
	{ word: "yeah", sentence: "Yeah, he did call me earlier." },
	{ word: "suggest", sentence: "He did suggest that to me." },
	{ word: "class", sentence: "We were in the same English class." },
	{ word: "control", sentence: "Where's the remote control?" },
	{
		word: "raise",
		sentence: "It's so challenging to discipline kids these days.",
	},
	{ word: "care", sentence: "I don't care about what you think." },
	{ word: "perhaps", sentence: "Perhaps we can arrive at a compromise." },
	{ word: "little", sentence: "There's a little bird outside my window." },
	{
		word: "late",
		sentence: "I am running late for my doctor's appointment.",
	},
	{ word: "hard", sentence: "That test was so hard." },
	{ word: "field", sentence: "He's over there, by the soccer field." },
	{ word: "else", sentence: "Is anyone else coming?" },
	{ word: "pass", sentence: "Can we pass by the grocery store?" },
	{ word: "former", sentence: "She was my former housemate." },
	{ word: "sell", sentence: "We can sell your old couch online." },
	{ word: "major", sentence: "It's a major issue for the project." },
	{
		word: "sometimes",
		sentence: "Sometimes I forget to turn off the porch lights.",
	},
	{ word: "require", sentence: "They'll require you to show your I.D." },
	{ word: "along", sentence: "Can I tag along your road trip?" },
	{
		word: "development",
		sentence: "This news development is really interesting.",
	},
	{ word: "themselves", sentence: "They can take care of themselves." },
	{ word: "report", sentence: "I read her report and it was great!" },
	{ word: "role", sentence: "She's going to play the role of Elsa." },
	{ word: "better", sentence: "Your singing has gotten so much better!" },
	{
		word: "economic",
		sentence: "Some countries are facing an economic crisis.",
	},
	{
		word: "effort",
		sentence: "The government must make an effort to solve this.",
	},
	{ word: "up", sentence: "His grades have gone up." },
	{ word: "decide", sentence: "Please decide where to eat." },
	{ word: "rate", sentence: "How would you rate the hotel's service?" },
	{ word: "strong", sentence: "They have strong customer service here!" },
	{
		word: "possible",
		sentence: "Maybe it's possible to change their bathroom amenities.",
	},
	{ word: "heart", sentence: "My heart is so full." },
	{
		word: "drug",
		sentence:
			"She got the patent for the drug she has created to cure cancer.",
	},
	{ word: "show", sentence: "Can you show me how to solve this puzzle?" },
	{ word: "leader", sentence: "You are a wonderful leader." },
	{
		word: "light",
		sentence: "Watch her face light up when you mention his name.",
	},
	{
		word: "voice",
		sentence: "Hearing his mom's voice is all he need right now.",
	},
	{ word: "wife", sentence: "My wife is away for the weekend." },
	{ word: "whole", sentence: "I have the whole house to myself." },
	{
		word: "police",
		sentence: "The police have questioned him about the incident.",
	},
	{
		word: "mind",
		sentence: "This relaxation technique really eases my mind.",
	},
	{
		word: "finally",
		sentence: "I can finally move out from my old apartment.",
	},
	{ word: "pull", sentence: "My baby niece likes to pull my hair." },
	{ word: "return", sentence: "I give her tickles in return." },
	{ word: "free", sentence: "The best things in life are free." },
	{ word: "military", sentence: "His dad is in the military." },
	{ word: "price", sentence: "This is the price you pay for lying." },
	{ word: "report", sentence: "Did you report this to the police?" },
	{
		word: "less",
		sentence: "I am praying for less stress this coming new year.",
	},
	{
		word: "according",
		sentence: "According to the weather report, it's going to rain today.",
	},
	{ word: "decision", sentence: "This is a big decision for me." },
	{ word: "explain", sentence: "I'll explain everything later, I promise." },
	{ word: "son", sentence: "His son is so cute!" },
	{ word: "hope", sentence: "I hope I'll have a son one day." },
	{
		word: "even",
		sentence: "Even if they've broken up, they still remain friends.",
	},
	{
		word: "develop",
		sentence: "That rash could develop into something more serious.",
	},
	{ word: "view", sentence: "This view is amazing!" },
	{
		word: "relationship",
		sentence: "They've taken their relationship to the next level.",
	},
	{ word: "carry", sentence: "Can you carry my bag for me?" },
	{ word: "town", sentence: "This town is extremely quiet." },
	{
		word: "road",
		sentence: "There's a road that leads to the edge of the woods.",
	},
	{ word: "drive", sentence: "You can't drive there, you need to walk." },
	{ word: "arm", sentence: "He broke his arm during practice." },
	{ word: "true", sentence: "It's true, I'm leaving the company." },
	{ word: "federal", sentence: "Animal abuse is now a federal felony!" },
	{ word: "break", sentence: "Don't break the law." },
	{ word: "better", sentence: "You better learn how to follow rules." },
	{
		word: "difference",
		sentence: "What's the difference between happiness and contentment?",
	},
	{
		word: "thank",
		sentence: "I forgot to thank her for the pie she sent us.",
	},
	{ word: "receive", sentence: "Did you receive the pie I sent you?" },
	{ word: "value", sentence: "I value our friendship so much." },
	{ word: "international", sentence: "Their brand has gone international!" },
	{ word: "building", sentence: "This building is so tall!" },
	{ word: "action", sentence: "You next action is going to be critical." },
	{ word: "full", sentence: "My work load is so full now." },
	{
		word: "model",
		sentence: "A great leader is a great model of how to do things.",
	},
	{ word: "join", sentence: "He wants to join the soccer team." },
	{ word: "season", sentence: "Christmas is my favorite season!" },
	{ word: "society", sentence: "Their society is holding a fund raiser." },
	{ word: "because", sentence: "I'm going home because my mom needs me." },
	{ word: "tax", sentence: "How much is the current income tax?" },
	{ word: "director", sentence: "The director yelled ‘Cut!'" },
	{ word: "early", sentence: "I'm too early for my appointment." },
	{
		word: "position",
		sentence: "Please position your hand properly when drawing.",
	},
	{ word: "player", sentence: "That basketball player is cute." },
	{ word: "agree", sentence: "I agree! He is cute!" },
	{ word: "especially", sentence: "I especially like his blue eyes." },
	{
		word: "record",
		sentence: "Can we record the minutes of this meeting, please?",
	},
	{ word: "pick", sentence: "Did you pick a color theme already?" },
	{
		word: "wear",
		sentence: "Is that what you're going to wear for the party?",
	},
	{
		word: "paper",
		sentence: "You can use a special paper for your invitations.",
	},
	{ word: "special", sentence: "Some special paper are even scented!" },
	{
		word: "space",
		sentence: "Please leave some space to write down your phone number.",
	},
	{ word: "ground", sentence: "The ground is shaking." },
	{
		word: "form",
		sentence: "A new island was formed after that big earthquake.",
	},
	{ word: "support", sentence: "I need your support for this project." },
	{ word: "event", sentence: "We're holding a big event tonight." },
	{ word: "official", sentence: "Our official wedding photos are out!" },
	{ word: "whose", sentence: "Whose umbrella is this?" },
	{ word: "matter", sentence: "What does it matter anyway?" },
	{ word: "everyone", sentence: "Everyone thinks I stole that file." },
	{ word: "center", sentence: "I hate being the center of attention." },
	{ word: "couple", sentence: "The couple is on their honeymoon now." },
	{ word: "site", sentence: "This site is so big!" },
	{ word: "end", sentence: "It's the end of an era." },
	{ word: "project", sentence: "This project file is due tomorrow." },
	{ word: "hit", sentence: "He hit the burglar with a bat." },
	{ word: "base", sentence: "All moms are their child's home base." },
	{
		word: "activity",
		sentence: "What musical activity can you suggest for my toddler?",
	},
	{ word: "star", sentence: "My son can draw a star!" },
	{
		word: "table",
		sentence: "I saw him draw it while he was writing on the table.",
	},
	{ word: "need", sentence: "I need to enroll him to a good preschool." },
	{ word: "court", sentence: "There's a basketball court near our house." },
	{ word: "produce", sentence: "Fresh farm produce is the best." },
	{ word: "eat", sentence: "I could eat that all day." },
	{ word: "American", sentence: "My sister is dating an American." },
	{ word: "teach", sentence: "I love to teach English lessons." },
	{
		word: "oil",
		sentence: "Could you buy me some cooking oil at the store?",
	},
	{ word: "half", sentence: "Just half a liter please." },
	{ word: "situation", sentence: "The situation is getting out of hand." },
	{ word: "easy", sentence: "I thought you said this was going to be easy?" },
	{ word: "cost", sentence: "The cost of fuel has increased!" },
	{ word: "industry", sentence: "The fuel industry is hiking prices." },
	{
		word: "figure",
		sentence: "Will our government figure out how to fix this problem?",
	},
	{
		word: "face",
		sentence:
			"I can't bear to face this horrendous traffic again and again.",
	},
	{ word: "street", sentence: "Let's cross the street." },
	{
		word: "image",
		sentence: "There's an image of him stored inside my mind.",
	},
	{ word: "itself", sentence: "The bike itself is pretty awesome." },
	{ word: "phone", sentence: "Plus, it has a phone holder." },
	{ word: "either", sentence: "I either walk or commute to work." },
	{ word: "data", sentence: "How can we simplify this data?" },
	{ word: "cover", sentence: "Could you cover for me during emergencies?" },
	{ word: "quite", sentence: "I'm quite satisfied with their work." },
	{
		word: "picture",
		sentence: "Picture this: a lake, a cabin, and lots of peace and quiet.",
	},
	{ word: "clear", sentence: "That picture is so clear inside my head." },
	{ word: "practice", sentence: "Let's practice our dance number." },
	{ word: "piece", sentence: "That's a piece of cake!" },
	{ word: "land", sentence: "Their plane is going to land soon." },
	{ word: "recent", sentence: "This is her most recent social media post." },
	{ word: "describe", sentence: "Describe yourself in one word." },
	{
		word: "product",
		sentence: "This is my favorite product in their new line of cosmetics.",
	},
	{ word: "doctor", sentence: "The doctor is in." },
	{ word: "wall", sentence: "Can you post this up on the wall?" },
	{ word: "patient", sentence: "The patient is in so much pain now." },
	{ word: "worker", sentence: "She's a factory worker." },
	{ word: "news", sentence: "I saw that on the news." },
	{ word: "test", sentence: "I have to pass this English test." },
	{ word: "movie", sentence: "Let's watch a movie later." },
	{
		word: "certain",
		sentence: "There's a certain kind of magic in the air now.",
	},
	{ word: "north", sentence: "Santa lives up north." },
	{ word: "love", sentence: "I love Christmas!" },
	{ word: "personal", sentence: "This letter is very personal." },
	{ word: "open", sentence: "Why did you open and read it?" },
	{ word: "support", sentence: "Will you support him?" },
	{ word: "simply", sentence: "I simply won't tolerate bad behavior." },
	{ word: "third", sentence: "This is the third time you've lied to me." },
	{
		word: "technology",
		sentence: "Write about the advantages of technology.",
	},
	{ word: "catch", sentence: "Let's catch up soon, please!" },
	{ word: "step", sentence: "Watch your step." },
	{ word: "baby", sentence: "Her baby is so adorable." },
	{ word: "computer", sentence: "Can you turn on the computer, please?" },
	{ word: "type", sentence: "You need to type in your password." },
	{ word: "attention", sentence: "Can I have your attention, please?" },
	{ word: "draw", sentence: "Can you draw this for me?" },
	{ word: "film", sentence: "That film is absolutely mind-blowing." },
	{ word: "Republican", sentence: "He is a Republican candidate." },
	{ word: "tree", sentence: "That tree has been there for generations." },
	{ word: "source", sentence: "You are my source of strength." },
	{ word: "red", sentence: "I'll wear a red dress tonight." },
	{ word: "nearly", sentence: "He nearly died in that accident!" },
	{
		word: "organization",
		sentence: "Their organization is doing great things for street kids.",
	},
	{ word: "choose", sentence: "Let me choose a color." },
	{
		word: "cause",
		sentence: "We have to see the cause and effect of this experiment.",
	},
	{ word: "hair", sentence: "I'll cut my hair short for a change." },
	{ word: "look", sentence: "Can you look at the items I bought?" },
	{ word: "point", sentence: "What is the point of all this?" },
	{ word: "century", sentence: "We're living in the 21st century, Mary." },
	{
		word: "evidence",
		sentence: "The evidence clearly shows that he is guilty.",
	},
	{ word: "window", sentence: "I'll buy window curtains next week." },
	{ word: "difficult", sentence: "Sometimes, life can be difficult." },
	{ word: "listen", sentence: "You have to listen to your teacher." },
	{ word: "soon", sentence: "I will launch my course soon." },
	{
		word: "culture",
		sentence: "I hope they understand our culture better.",
	},
	{
		word: "billion",
		sentence:
			"My target is to have 1 billion dollars in my account by the end of the year.",
	},
	{
		word: "chance",
		sentence: "Is there any chance that you can do this for me?",
	},
	{ word: "brother", sentence: "My brother always have my back." },
	{ word: "energy", sentence: "Now put that energy into walking." },
	{ word: "period", sentence: "They covered a period of twenty years." },
	{ word: "course", sentence: "Have seen my course already?" },
	{ word: "summer", sentence: "I'll go to the beach in summer." },
	{ word: "less", sentence: "Sometimes, less is more." },
	{
		word: "realize",
		sentence: "I just realize that I have a meeting today.",
	},
	{
		word: "hundred",
		sentence: "I have a hundred dollars that I can lend you.",
	},
	{ word: "available", sentence: "I am available to work on your project." },
	{ word: "plant", sentence: "Plant a seed." },
	{ word: "likely", sentence: "It was likely a deer trail." },
	{
		word: "opportunity",
		sentence: "It was the perfect opportunity to test her theory.",
	},
	{ word: "term", sentence: "I'm sure there's a Latin term for it." },
	{ word: "short", sentence: "It was just a short stay at the hotel." },
	{ word: "letter", sentence: "I already passed my letter of intent." },
	{ word: "condition", sentence: "Do you know the condition I am in?" },
	{ word: "choice", sentence: "I have no choice." },
	{ word: "place", sentence: "Let's meet out at meeting place." },
	{ word: "single", sentence: "I am a single parent." },
	{ word: "rule", sentence: "It's the rule of the law." },
	{ word: "daughter", sentence: "My daughter knows how to read now." },
	{
		word: "administration",
		sentence: "I will take this up with the administration.",
	},
	{ word: "south", sentence: "I am headed south." },
	{
		word: "husband",
		sentence: "My husband just bought me a ring for my birthday.",
	},
	{ word: "Congress", sentence: "It will be debated at the Congress." },
	{ word: "floor", sentence: "She is our floor manager." },
	{ word: "campaign", sentence: "I handled their election campaign." },
	{ word: "material", sentence: "She had nothing material to report." },
	{
		word: "population",
		sentence: "The population of the nearest big city was growing.",
	},
	{ word: "well", sentence: "I wish you well." },
	{ word: "call", sentence: "I am going to call the bank." },
	{ word: "economy", sentence: "The economy is booming." },
	{ word: "medical", sentence: "She needs medical assistance." },
	{ word: "hospital", sentence: "I'll take her to the nearest hospital." },
	{ word: "church", sentence: "I saw you in church last Sunday." },
	{ word: "close", sentence: "Please close the door." },
	{
		word: "thousand",
		sentence: "There are a thousand reasons to learn English!",
	},
	{ word: "risk", sentence: "Taking a risk can be rewarding." },
	{ word: "current", sentence: "What is your current address?" },
	{
		word: "fire",
		sentence: "Make sure your smoke alarm works in case of fire.",
	},
	{ word: "future", sentence: "The future is full of hope." },
	{ word: "wrong", sentence: "That is the wrong answer." },
	{ word: "involve", sentence: "We need to involve the police." },
	{
		word: "defense",
		sentence: "What is your defense or reason you did this?",
	},
	{ word: "anyone", sentence: "Does anyone know the answer?" },
	{ word: "increase", sentence: "Let's increase your test score." },
	{ word: "security", sentence: "Some apartment buildings have security." },
	{
		word: "bank",
		sentence: "I need to go to the bank to withdraw some money.",
	},
	{ word: "myself", sentence: "I can clean up by myself." },
	{ word: "certainly", sentence: "I can certainly help clean up." },
	{
		word: "west",
		sentence: "If you drive West, you will arrive in California.",
	},
	{ word: "sport", sentence: "My favorite sport is soccer." },
	{ word: "board", sentence: "Can you see the board?" },
	{ word: "seek", sentence: "Seek and you will find." },
	{ word: "per", sentence: "Lobster is $20 per pound." },
	{ word: "subject", sentence: "My favorite subject is English!" },
	{ word: "officer", sentence: "Where can I find a police officer?" },
	{ word: "private", sentence: "This is a private party." },
	{ word: "rest", sentence: "Let's take a 15 minute rest." },
	{ word: "behavior", sentence: "This dog's behavior is excellent." },
	{ word: "deal", sentence: "A used car can be a good deal." },
	{
		word: "performance",
		sentence: "Your performance can be affected by your sleep.",
	},
	{ word: "fight", sentence: "I don't want to fight with you." },
	{ word: "throw", sentence: "Throw me the ball!" },
	{ word: "top", sentence: "You are a top student." },
	{ word: "quickly", sentence: "Let's finish reading this quickly." },
	{
		word: "past",
		sentence: "In the past, my English was not as good as it is today.",
	},
	{ word: "goal", sentence: "My goal is to speak English fluently." },
	{
		word: "second",
		sentence: "My second goal is to increase my confidence.",
	},
	{ word: "bed", sentence: "I go to bed around 10pm." },
	{ word: "order", sentence: "I would like to order a book." },
	{ word: "author", sentence: "The author of this series is world-famous." },
	{ word: "fill", sentence: "I need to fill (up) my gas tank." },
	{ word: "represent", sentence: "I represent my family." },
	{
		word: "focus",
		sentence: "Turn off your phone and the TV and focus on your studies!",
	},
	{ word: "foreign", sentence: "It's great having foreign friends." },
	{ word: "drop", sentence: "Please don't drop the eggs!" },
	{ word: "plan", sentence: "Let's make a plan." },
	{ word: "blood", sentence: "The hospital needs people to give blood." },
	{
		word: "upon",
		sentence: "Once upon a time, a princess lived in a castle.",
	},
	{
		word: "agency",
		sentence: "Let's contract an agency to help with marketing.",
	},
	{ word: "push", sentence: "The door says ‘push,' not ‘pull.'" },
	{ word: "nature", sentence: "I love walking in nature!" },
	{ word: "color", sentence: "My favorite color is blue." },
	{ word: "no", sentence: "‘No' is one of the shortest complete sentences." },
	{
		word: "recently",
		sentence:
			"I cleaned the bathroom most recently, so I think it's your turn this time.",
	},
	{ word: "store", sentence: "I'm going to the store to buy some bread." },
	{
		word: "reduce",
		sentence:
			"Reduce, reuse, and recycle are the ways to help the environment.",
	},
	{ word: "sound", sentence: "I like the sound of wind chimes." },
	{ word: "note", sentence: "Please take notes during the lesson." },
	{ word: "fine", sentence: "I feel fine." },
	{ word: "before", sentence: "Before the movie, let's buy popcorn!" },
	{
		word: "near",
		sentence:
			"Near, far, wherever you are, I do believe that the heart goes on.",
	},
	{
		word: "movement",
		sentence: "The environmental movement is an international movement.",
	},
	{ word: "page", sentence: "Please turn to page 62." },
	{ word: "enter", sentence: "You can enter the building on the left." },
	{ word: "share", sentence: "Let me share my idea." },
	{ word: "than", sentence: "Ice cream has more calories than water." },
	{
		word: "common",
		sentence: "Most people can find something in common with each other.",
	},
	{
		word: "poor",
		sentence: "We had a poor harvest this year because it was so dry.",
	},
	{ word: "other", sentence: "This pen doesn't work, try the other one." },
	{
		word: "natural",
		sentence: "This cleaner is natural, there aren't any chemicals in it.",
	},
	{ word: "race", sentence: "We watched the car race on TV." },
	{ word: "concern", sentence: "Thank you for your concern, but I'm fine." },
	{ word: "series", sentence: "What is your favorite TV series?" },
	{
		word: "significant",
		sentence: "His job earns a significant amount of money.",
	},
	{
		word: "similar",
		sentence: "These earrings don't match, but they are similar.",
	},
	{ word: "hot", sentence: "Don't touch the stove, it's still hot." },
	{ word: "language", sentence: "Learning a new language is fun." },
	{ word: "each", sentence: "Put a flower in each vase." },
	{ word: "usually", sentence: "I usually shop at the corner store." },
	{
		word: "response",
		sentence: "I didn't expect his response to come so soon.",
	},
	{ word: "dead", sentence: "My phone is dead, let me charge it." },
	{ word: "rise", sentence: "The sun will rise at 7:00 a.m." },
	{ word: "animal", sentence: "What kind of animal is that?" },
	{
		word: "factor",
		sentence: "Heredity is a factor in your overall health.",
	},
	{ word: "decade", sentence: "I've lived in this city for over a decade." },
	{ word: "article", sentence: "Did you read that newspaper article?" },
	{ word: "shoot", sentence: "He wants to shoot arrows at the target." },
	{ word: "east", sentence: "Drive east for three miles." },
	{ word: "save", sentence: "I save all my cans for recycling." },
	{ word: "seven", sentence: "There are seven slices of pie left." },
	{ word: "artist", sentence: "Taylor Swift is a recording artist." },
	{ word: "away", sentence: "I wish that mosquito would go away." },
	{ word: "scene", sentence: "He painted a colorful street scene." },
	{ word: "stock", sentence: "That shop has a good stock of postcards." },
	{
		word: "career",
		sentence: "Retail sales is a good career for some people.",
	},
	{
		word: "despite",
		sentence: "Despite the rain, we will still have the picnic.",
	},
	{ word: "central", sentence: "There is good shopping in central London." },
	{ word: "eight", sentence: "That recipe takes eight cups of flour." },
	{ word: "thus", sentence: "We haven't had any problems thus far." },
	{
		word: "treatment",
		sentence: "I will propose a treatment plan for your injury.",
	},
	{ word: "beyond", sentence: "The town is just beyond those mountains." },
	{ word: "happy", sentence: "Kittens make me happy." },
	{
		word: "exactly",
		sentence: "Use exactly one teaspoon of salt in that recipe.",
	},
	{
		word: "protect",
		sentence: "A coat will protect you from the cold weather.",
	},
	{ word: "approach", sentence: "The cat slowly approached the bird." },
	{ word: "lie", sentence: "Teach your children not to lie." },
	{ word: "size", sentence: "What size is that shirt?" },
	{ word: "dog", sentence: "Do you think a dog is a good pet?" },
	{ word: "fund", sentence: "I have a savings fund for college." },
	{ word: "serious", sentence: "She is so serious, she never laughs." },
	{ word: "occur", sentence: "Strange things occur in that empty house." },
	{ word: "media", sentence: "That issue has been discussed in the media." },
	{ word: "ready", sentence: "Are you ready to leave for work?" },
	{ word: "sign", sentence: "That store needs a bigger sign." },
	{ word: "thought", sentence: "I'll have to give it some thought." },
	{ word: "list", sentence: "I made a list of things to do." },
	{
		word: "individual",
		sentence: "You can buy an individual or group membership.",
	},
	{
		word: "simple",
		sentence: "The appliance comes with simple instructions.",
	},
	{ word: "quality", sentence: "I paid a little more for quality shoes." },
	{ word: "pressure", sentence: "There is no pressure to finish right now." },
	{ word: "accept", sentence: "Will you accept my credit card?" },
	{ word: "answer", sentence: "Give me your answer by noon tomorrow." },
	{ word: "hard", sentence: "That test was very hard." },
	{ word: "resource", sentence: "The library has many online resources." },
	{ word: "identify", sentence: "I can't identify that plant." },
	{ word: "left", sentence: "The door is on your left as you approach." },
	{ word: "meeting", sentence: "We'll have a staff meeting after lunch." },
	{ word: "determine", sentence: "Eye color is genetically determined." },
	{ word: "prepare", sentence: "I'll prepare breakfast tomorrow." },
	{ word: "disease", sentence: "Face masks help prevent disease." },
	{ word: "whatever", sentence: "Choose whatever flavor you like the best." },
	{ word: "success", sentence: "Failure is the back door to success." },
	{
		word: "argue",
		sentence: "It's not a good idea to argue with your boss.",
	},
	{ word: "cup", sentence: "Would you like a cup of coffee?" },
	{
		word: "particularly",
		sentence: "It's not particularly hot outside, just warm.",
	},
	{
		word: "amount",
		sentence: "It take a large amount of food to feed an elephant.",
	},
	{ word: "ability", sentence: "He has the ability to explain things well." },
	{ word: "staff", sentence: "There are five people on staff here." },
	{
		word: "recognize",
		sentence: "Do you recognize the person in this photo?",
	},
	{ word: "indicate", sentence: "Her reply indicated that she understood." },
	{ word: "character", sentence: "You can trust people of good character." },
	{
		word: "growth",
		sentence: "The company has seen strong growth this quarter.",
	},
	{
		word: "loss",
		sentence: "The farmer suffered heavy losses after the storm.",
	},
	{ word: "degree", sentence: "Set the oven to 300 degrees." },
	{ word: "wonder", sentence: "I wonder if the Bulls will win the game." },
	{ word: "attack", sentence: "The army will attack at dawn." },
	{ word: "herself", sentence: "She bought herself a new coat." },
	{ word: "region", sentence: "What internet services are in your region?" },
	{ word: "television", sentence: "I don't watch much television." },
	{ word: "box", sentence: "I packed my dishes in a strong box." },
	{ word: "TV", sentence: "There is a good movie on TV tonight." },
	{ word: "training", sentence: "The company will pay for your training." },
	{ word: "pretty", sentence: "That is a pretty dress." },
	{ word: "trade", sentence: "The stock market traded lower today." },
	{ word: "deal", sentence: "I got a good deal at the store." },
	{ word: "election", sentence: "Who do you think will win the election?" },
	{ word: "everybody", sentence: "Everybody likes ice cream." },
	{ word: "physical", sentence: "Keep a physical distance of six feet." },
	{ word: "lay", sentence: "Lay the baby in her crib, please." },
	{
		word: "general",
		sentence: "My general impression of the restaurant was good.",
	},
	{ word: "feeling", sentence: "I have a good feeling about this." },
	{ word: "standard", sentence: "The standard fee is $10.00." },
	{ word: "bill", sentence: "The electrician will send me a bill." },
	{ word: "message", sentence: "You have a text message on your phone." },
	{ word: "fail", sentence: "I fail to see what is so funny about that." },
	{ word: "outside", sentence: "The cat goes outside sometimes." },
	{ word: "arrive", sentence: "When will your plane arrive?" },
	{
		word: "analysis",
		sentence: "I'll give you my analysis when I've seen everything.",
	},
	{ word: "benefit", sentence: "There are many health benefits to quinoa." },
	{ word: "name", sentence: "What's your name?" },
	{ word: "sex", sentence: "Do you know the sex of your baby yet?" },
	{ word: "forward", sentence: "Move the car forward a few feet." },
	{ word: "lawyer", sentence: "My lawyer helped me write a will." },
	{
		word: "present",
		sentence: "If everyone is present, the meeting can begin.",
	},
	{
		word: "section",
		sentence: "What section of the stadium are you sitting in?",
	},
	{
		word: "environmental",
		sentence: "Environmental issues are in the news.",
	},
	{ word: "glass", sentence: "Glass is much heavier than plastic." },
	{ word: "answer", sentence: "Could you answer a question for me?" },
	{ word: "skill", sentence: "His best skill is woodworking." },
	{ word: "sister", sentence: "My sister lives close to me." },
	{ word: "PM", sentence: "The movie starts at 7:30 PM." },
	{ word: "professor", sentence: "Dr. Smith is my favorite professor." },
	{
		word: "operation",
		sentence: "The mining operation employs thousands of people.",
	},
	{
		word: "financial",
		sentence: "I keep my accounts at my financial institution.",
	},
	{ word: "crime", sentence: "The police fight crime." },
	{
		word: "stage",
		sentence: "A caterpillar is the larval stage of a butterfly.",
	},
	{ word: "ok", sentence: "Would it be ok to eat out tonight?" },
	{ word: "compare", sentence: "We should compare cars before we buy one." },
	{ word: "authority", sentence: "City authorities make the local laws." },
	{ word: "miss", sentence: "I miss you, when will I see you again?" },
	{ word: "design", sentence: "We need to design a new logo." },
	{ word: "sort", sentence: "Let's sort these beads according to color." },
	{ word: "one", sentence: "I only have one cat." },
	{ word: "act", sentence: "I'll act on your information today." },
	{ word: "ten", sentence: "The baby counted her ten toes." },
	{ word: "knowledge", sentence: "Do you have the knowledge to fix that?" },
	{ word: "gun", sentence: "Gun ownership is a controversial topic." },
	{
		word: "station",
		sentence: "There is a train station close to my house.",
	},
	{ word: "blue", sentence: "My favorite color is blue." },
	{
		word: "state",
		sentence: "After the accident I was in a state of shock.",
	},
	{
		word: "strategy",
		sentence: "Our new corporate strategy is written here.",
	},
	{ word: "little", sentence: "I prefer little cars." },
	{ word: "clearly", sentence: "The instructions were clearly written." },
	{ word: "discuss", sentence: "We'll discuss that at the meeting." },
	{ word: "indeed", sentence: "Your mother does indeed have hearing loss." },
	{ word: "force", sentence: "It takes a lot of force to open that door." },
	{ word: "truth", sentence: "Please tell me the truth." },
	{ word: "song", sentence: "That's a beautiful song." },
	{
		word: "example",
		sentence: "I need an example of that grammar point, please.",
	},
	{
		word: "democratic",
		sentence: "Does Australia have a democratic government?",
	},
	{
		word: "check",
		sentence: "Please check my work to be sure it's correct.",
	},
	{ word: "environment", sentence: "We live in a healthy environment." },
	{ word: "leg", sentence: "The boy broke his leg." },
	{ word: "dark", sentence: "Turn on the light, it's dark in here." },
	{ word: "public", sentence: "Masks must be worn in public places." },
	{ word: "various", sentence: "That rug comes in various shades of gray." },
	{
		word: "rather",
		sentence: "Would you rather have a hamburger than a hot dog?",
	},
	{ word: "laugh", sentence: "That movie always makes me laugh." },
	{ word: "guess", sentence: "If you don't know, just guess." },
	{ word: "executive", sentence: "The company's executives are paid well." },
	{ word: "set", sentence: "Set the glass on the table, please." },
	{ word: "study", sentence: "He needs to study for the test." },
	{ word: "prove", sentence: "The employee proved his worth." },
	{ word: "hang", sentence: "Please hang your coat on the hook." },
	{ word: "entire", sentence: "He ate the entire meal in 10 minutes." },
	{ word: "rock", sentence: "There are decorative rocks in the garden." },
	{ word: "design", sentence: "The windows don't open by design." },
	{ word: "enough", sentence: "Have you had enough coffee?" },
	{ word: "forget", sentence: "Don't forget to stop at the store." },
	{ word: "since", sentence: "She hasn't eaten since yesterday." },
	{
		word: "claim",
		sentence: "I made an insurance claim for my car accident.",
	},
	{ word: "note", sentence: "Leave me a note if you're going to be late." },
	{ word: "remove", sentence: "Remove the cookies from the oven." },
	{ word: "manager", sentence: "The manager will look at your application." },
	{ word: "help", sentence: "Could you help me move this table?" },
	{ word: "close", sentence: "Close the door, please." },
	{ word: "sound", sentence: "The dog did not make a sound." },
	{ word: "enjoy", sentence: "I enjoy soda." },
	{ word: "network", sentence: "Band is the name of our internet network." },
	{ word: "legal", sentence: "The legal documents need to be signed." },
	{
		word: "religious",
		sentence: "She is very religious, she attends church weekly.",
	},
	{ word: "cold", sentence: "My feet are cold." },
	{ word: "form", sentence: "Please fill out this application form." },
	{ word: "final", sentence: "The divorce was final last month." },
	{ word: "main", sentence: "The main problem is a lack of money." },
	{
		word: "science",
		sentence: "He studies health science at the university.",
	},
	{ word: "green", sentence: "The grass is green." },
	{ word: "memory", sentence: "He has a good memory." },
	{ word: "card", sentence: "They sent me a card for my birthday." },
	{ word: "above", sentence: "Look on the shelf above the sink." },
	{ word: "seat", sentence: "That's a comfortable seat." },
	{ word: "cell", sentence: "Your body is made of millions of cells." },
	{ word: "establish", sentence: "They established their business in 1942." },
	{ word: "nice", sentence: "That's a very nice car." },
	{ word: "trial", sentence: "They are employing her on a trial basis." },
	{ word: "expert", sentence: "Matt is an IT expert." },
	{ word: "that", sentence: "Did you see that movie?" },
	{ word: "spring", sentence: "Spring is the most beautiful season." },
	{
		word: "firm",
		sentence: "Her decision was very firm, she won't change her mind.",
	},
	{ word: "Democrat", sentence: "The Democrats control the Senate." },
	{ word: "radio", sentence: "I listen to the radio in the car." },
	{ word: "visit", sentence: "We visited the museum today." },
	{ word: "management", sentence: "That store has good management." },
	{ word: "care", sentence: "She cares for her mother at home." },
	{ word: "avoid", sentence: "You should avoid poison ivy." },
	{ word: "imagine", sentence: "Can you imagine if pigs could fly?" },
	{ word: "tonight", sentence: "Would you like to go out tonight?" },
	{ word: "huge", sentence: "That truck is huge!" },
	{ word: "ball", sentence: "He threw the ball to the dog." },
	{ word: "no", sentence: "I said ‘no,' please don't ask again." },
	{ word: "close", sentence: "Close the window, please." },
	{ word: "finish", sentence: "Did you finish your homework?" },
	{ word: "yourself", sentence: "You gave yourself a haircut?" },
	{ word: "talk", sentence: "He talks a lot." },
	{ word: "theory", sentence: "In theory, that's a good plan." },
	{ word: "impact", sentence: "The drought had a big impact on the crops." },
	{ word: "respond", sentence: "He hasn't responded to my text yet." },
	{
		word: "statement",
		sentence: "The police chief gave a statement to the media.",
	},
	{
		word: "maintain",
		sentence: "Exercise helps you maintain a healthy weight.",
	},
	{ word: "charge", sentence: "I need to charge my phone." },
	{ word: "popular", sentence: "That's a popular restaurant." },
	{
		word: "traditional",
		sentence: "They serve traditional Italian food there.",
	},
	{ word: "onto", sentence: "Jump onto the boat and we'll go fishing." },
	{
		word: "reveal",
		sentence: "Washing off the dirt revealed the boy's skinned knee.",
	},
	{ word: "direction", sentence: "What direction is the city from here?" },
	{
		word: "weapon",
		sentence: "No weapons are allowed in government buildings.",
	},
	{ word: "employee", sentence: "That store only has three employees." },
	{
		word: "cultural",
		sentence: "There is cultural significance to those old ruins.",
	},
	{ word: "contain", sentence: "The carton contains a dozen egges." },
	{ word: "peace", sentence: "World leaders gathered for peace talks." },
	{ word: "head", sentence: "My head hurts." },
	{ word: "control", sentence: "Keep control of the car." },
	{
		word: "base",
		sentence: "The glass has a heavy base so it won't fall over.",
	},
	{ word: "pain", sentence: "I have chest pain." },
	{ word: "apply", sentence: "Maria applied for the job." },
	{ word: "play", sentence: "The children play at the park." },
	{ word: "measure", sentence: "Measure twice, cut once." },
	{ word: "wide", sentence: "The doorway was very wide." },
	{ word: "shake", sentence: "Don't shake the can of soda." },
	{ word: "fly", sentence: "We can fly to France next year." },
	{ word: "interview", sentence: "My job interview went well." },
	{ word: "manage", sentence: "Did you manage to find the keys?" },
	{ word: "chair", sentence: "The table has six matching chairs." },
	{ word: "fish", sentence: "I don't enjoy eating fish." },
	{
		word: "particular",
		sentence: "That particular style looks good on you.",
	},
	{ word: "camera", sentence: "I use the camera on my phone." },
	{ word: "structure", sentence: "The building's structure is solid." },
	{ word: "politics", sentence: "Mitch is very active in politics." },
	{ word: "perform", sentence: "The singer will perform tonight." },
	{ word: "bit", sentence: "It rained a little bit last night." },
	{ word: "weight", sentence: "Keep track of your pet's weight." },
	{ word: "suddenly", sentence: "The storm came up suddenly." },
	{
		word: "discover",
		sentence: "You'll discover treasures at that thrift store.",
	},
	{
		word: "candidate",
		sentence: "There are ten candidates for the position.",
	},
	{ word: "top", sentence: "The flag flies on the top of that building." },
	{
		word: "production",
		sentence: "Factory production has improved over the summer.",
	},
	{ word: "treat", sentence: "Give yourself a treat for a job well done." },
	{ word: "trip", sentence: "We are taking a trip to Florida in January." },
	{ word: "evening", sentence: "I'm staying home this evening." },
	{
		word: "affect",
		sentence: "My bank account will affect how much I can buy.",
	},
	{ word: "inside", sentence: "The cat stays inside." },
	{
		word: "conference",
		sentence: "There will be expert presenters at the conference.",
	},
	{ word: "unit", sentence: "A foot is a unit of measure." },
	{ word: "best", sentence: "Those are the best glasses to buy." },
	{ word: "style", sentence: "My dress is out of style." },
	{
		word: "adult",
		sentence: "Adults pay full price, but children are free.",
	},
	{ word: "worry", sentence: "Don't worry about tomorrow." },
	{ word: "range", sentence: "My doctor offered me a range of options." },
	{ word: "mention", sentence: "Can you mention me in your story?" },
	{
		word: "rather",
		sentence:
			"Rather than focusing on the bad things, let's be grateful for the good things.",
	},
	{ word: "far", sentence: "I don't want to move far from my family." },
	{ word: "deep", sentence: "That poem about life is deep." },
	{ word: "front", sentence: "Please face front." },
	{
		word: "edge",
		sentence: "Please do not stand so close to the edge of the cliff.",
	},
	{
		word: "individual",
		sentence:
			"These potato chips are in an individual serving size package.",
	},
	{ word: "specific", sentence: "Could you be more specific?" },
	{ word: "writer", sentence: "You are a good writer." },
	{ word: "trouble", sentence: "Stay out of trouble." },
	{ word: "necessary", sentence: "It is necessary to sleep." },
	{
		word: "throughout",
		sentence: "Throughout my life I have always enjoyed reading.",
	},
	{ word: "challenge", sentence: "I challenge you to do better." },
	{ word: "fear", sentence: "Do you have any fears?" },
	{
		word: "shoulder",
		sentence: "You do not have to shoulder all the work on your own.",
	},
	{
		word: "institution",
		sentence: "Have you attended any institution of higher learning?",
	},
	{
		word: "middle",
		sentence:
			"I am a middle child with one older brother and one younger sister.",
	},
	{ word: "sea", sentence: "I want to sail the seven seas." },
	{ word: "dream", sentence: "I have a dream." },
	{ word: "bar", sentence: "A bar is a place where alcohol is served." },
	{ word: "beautiful", sentence: "You are beautiful." },
	{ word: "property", sentence: "Do you own property, like a house?" },
	{ word: "instead", sentence: "Instead of eating cake I will have fruit." },
	{ word: "improve", sentence: "I am always looking for ways to improve." },
	{
		word: "stuff",
		sentence: "When I moved, I realized I have a lot of stuff!",
	},
	{
		word: "claim",
		sentence: "I claim to be a fast reader, but actually I am average.",
	},
];
